### ISSUE TITLE
Problem with building a static binary

### ISSUE THREAD

**Issue by JeroenSoeters** [rust-bpf/bcc-sys#20]
## What did I expect? ##
When trying to build a static library using `cargo build --features v0_10_0 static` I would have expected that cargo would try to link against a statically compiled LLVM.

## What actually happened? ##
Instead cargo tried linking against a dynamically compiled LLVM. The error message I got was:

```console
vagrant@ubuntu-bionic:~/rust-bpf/bcc-sys$ cargo build --features v0_10_0 static
   Compiling bcc-sys v0.10.3-alpha.0 (/home/vagrant/rust-bpf/bcc-sys)
error: could not find native static library 'LLVM-6.0', perhaps an -L flag is missing?

error: aborting due to previous error

error: Could not compile 'bcc-sys'.

To learn more, run the command again with --verbose.
```

There is no libllvm-6.0.a file and from what I understand from running `llvm-config --libs --link-static` you need to compile against all the static libraries that this command outputs. Adding `.args(--link-static)` to the `build.rs` fixed the issue for me. I'm happy to open a PR with this fix.

## What steps can we take to reproduce the behaviour you saw? ##
I'm running ubuntu 18.04 with version 6.0 of the LLVM toolchain. Other steps are described above.

**Comment by brayniac** [comment]
Thanks for opening this. The static linking is a little weird - and hard to test in CI with the long build times. When I've used the static option, I actually build all of the toolchain and some non-obvious dependencies from source. This would definitely be an area to document better.

Here's the versions that I build and install from sources: (`export CFLAGS="-fPIC"` before builds) I actually set the install prefix for each to a local folder to avoid system-wide install. Then I update the rustflags variable to match `export RUSTFLAGS="-L ${PREFIX}/lib -L ${PREFIX}/lib64"`

zlib-1.2.7.tar.bz2
xz-5.2.2.tar.gz
ncurses-6.0.tar.gz (--with-termlib)
libxml2-2.9.1.tar.gz (--without-python)
elfutils-0.170.tar.bz2
llvm-8.0.0.src.tar.xz (-DLLVM_TARGETS_TO_BUILD='BPF;X86')
cfe-8.0.0.src.tar.xz
bcc-0.10.0.tar.gz

And after bcc is built, copy the .a files to the install folders.
`find . -name "*.a" -exec cp {} ${PREFIX}/lib/ \;`

The current build.rs works in combination with the above. At the time, I hadn't found a much better way to deal with this - curious if we can improve the build itself, or at least just the documentation.
